In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/ads.csv')
df.head()

,ad_id,advertiser_name,keywords,bid_price,quality_score,historical_clicks,historical_impressions
0,8ee34d58-0ac2-5e00-ba0b-4ad4958706eb,"Rodriguez, Figueroa and Sanchez",fashion|jackets,3.64,8.73,481,4268
1,bff8799c-d478-59aa-b893-e052d8502907,Doyle Ltd,jackets|jeans,2.53,2.15,841,15785
2,e8adf9db-dcb6-599c-a69c-eee41dbedcde,"Mcclain, Miller and Henderson",beauty|education,2.50,8.40,1221,9174
3,db5413c4-8297-5558-b3ed-4ee87c2b2cfd,Davis and Sons,books|shoes,3.91,6.68,1549,16604
4,876d705a-6329-56e4-a765-c95a6799be05,"Guzman, Hoffman and Baldwin",finance|headphones,1.38,8.01,953,7468

In [4]:
df2 = pd.read_csv('data/interactions.csv')
df2.head()

,interaction_id,user_id,query,query_length,ad_id,keyword_match_type,quality_score,historical_ctr,clicked
0,bcb8a465-6d61-57e5-a46e-8d99114ba3d8,user_4197,education gaming,2,ce45c62b-1eaf-55b1-a460-ce564decb4de,exact,6.29,0.106283,0
1,f8969132-2592-533c-be1c-c578e44e4439,user_2256,headphones hotel,2,8032ac25-9b9d-5772-bce7-47dc640bc4c6,exact,4.85,0.080109,0
2,51d90caa-ba8c-5a25-aea6-5c5c7ba2486b,user_21,electronics finance,2,531398bc-7e18-5a04-b53b-4420f99b4b6e,exact,8.30,0.114051,0
3,c0500f18-8ed8-5b3b-bcc5-0e81319e3cc2,user_4664,laptop running workout,3,814c2961-a56b-5521-87eb-6adb7a0738a4,broad,9.40,0.188873,0
4,033a8ec3-8e48-574b-bb75-f2328d2cee5e,user_4225,smartphone sneakers,2,61015c3f-f878-5f40-92e4-41b4fdab26aa,exact,5.57,0.098174,0

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   interaction_id      50000 non-null  object
 1   user_id             50000 non-null  object
 2   query               50000 non-null  object
 3   query_length        50000 non-null  int64
 4   ad_id               50000 non-null  object
 5   keyword_match_type  50000 non-null  object
 6   quality_score       50000 non-null  float64
 7   historical_ctr      50000 non-null  float64
 8   clicked             50000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 3.4+ MB